### ISSUE TITLE
Extend to cope with converted WARC records

### ISSUE THREAD

**Issue by anjackson** [ukwa/webarchive-discovery#111]
Some of our older WARCs were migrated from other sources (HTTrack/ARC). This has lead to the generation of `WARC conversion` records. e.g. 

```
WARC/1.0
WARC-Type: conversion
WARC-Target-URI: http://www.dur.ac.uk/175/index.html
WARC-Date: 2010-05-18T12:27:48Z
WARC-Record-ID: fedc289b-27a9-4505-aba4-ee11b77af7aa
WARC-Refers-To: d448e710-2d3a-4ffd-9cd5-3a81590d1ad3
WARC-Block-Digest: sha512:63e3073d6330b5342bbc6de22b9f75b35fe1782e5946e0e0c13e998eecce3650678a38c719680077de00a296542f9c768fdbb18b3867fd89c8492fdde5396157
Content-Type: text/html
Content-Length: 879
```

The error happens because the hash is done differently (SHA512 when it's expecting a SHA1). 

We should disable the hash check if a different algorithm has been used (don't compare `sha512:` against `sha1:`). We should also verify whether the system is able to skip these records (I guess the hash comparison happens before the filtering?).

The error ends up manifesting itself as `java.lang.RuntimeException java.io.EOFException: End of data reached.: Exception from Tika`

Example file (internal use only): `BL-99742-0.warc.gz`

Ideally, we should find an appropriately-licensed file of modest site and add that to this repo for testing.

**Comment by anjackson** [comment]
So @min2ha first step will be to set yourself up so you can run the indexer locally. This documentation should help: https://github.com/ukwa/webarchive-discovery/wiki/Quick-Start

**Comment by anjackson** [comment]
Just it be clear, and for @GilHoggarth, these `conversion` records should *not* be indexed. The question is whether we can set the indexer up to skip them correctly.

**Comment by anjackson** [comment]
https://wiki.bl.uk:8443/display/WAG/WARC+Files#WARCFiles-conversion

**Comment by anjackson** [comment]
Ah-ha. The error is thrown here:

https://github.com/ukwa/webarchive-discovery/blob/63ed4712c10b18970240d75fe31328abeae6ff20/warc-indexer/src/main/java/uk/bl/wa/util/HashedCachedInputStream.java#L159-L160

**Comment by min2ha** [comment]
Should we:
1. Just remove **check of the equality of hashes** or 
2. Get **exact version of hashes**: SHA512 or SHA1 (if it is possible) in order to avoid hash check failes? 

https://github.com/ukwa/webarchive-discovery/blob/63ed4712c10b18970240d75fe31328abeae6ff20/warc-indexer/src/main/java/uk/bl/wa/util/HashedCachedInputStream.java#L151-L158

**Comment by min2ha** [comment]
The compare the lengths of SHA hashes, should solve problem in most cases.
SHA sizes:
160 bits in the output of SHA-1
224 bits in the output of SHA-224
256 bits in the output of SHA-256
384 bits in the output of SHA-384
512 bits in the output of SHA-512
224 bits in the output of SHA-512/224
256 bits in the output of SHA-512/256

Anyway, there are some exceptions:
SHA-256 is actually SHA-2 256, and the SHA-3 competition will produce the same size outputs as SHA-2, as this is a requirement from NIST, who organize the competition. Naming is still an issue, but SHA-3-256 (etc.) would be a probable candidate. SHA-512 is faster on 64 bit machines than SHA-256 because it is optimized for 64 bit machines - and it still provides a larger security margin.

**Comment by anjackson** [comment]
Is this actually working for you locally now? Looking through the code I don't really understand why it wasn't working in the first place, because it seems to only apply to `response` type records rather than `conversion` records.

**Comment by min2ha** [comment]
The only difference now it is, that the **error is NOT thrown if the algorithms differs**, so hash check was disabled in this particular case as requested.

**Comment by anjackson** [comment]
I think we need to do a test run on the cluster, when @GilHoggarth has time.

**Comment by anjackson** [comment]
Looks good.
