### ISSUE TITLE
Minor: Some fields both docValues+stored  on same field (intended?)

### ISSUE THREAD

**Issue by thomasegense** [ukwa/webarchive-discovery#114]
When a field is docValues="true" the field can already be retrieved so making it stored just takes up additional index storage. It is intended?

The retrieval of a full document will in theory be faster when fields are also stored, but this is insignificant and we are not doing so on the majority of the docValues=true fields.

The following fields are both docValues and stored:
```
   <field name="last_modified" type="tdate" indexed="true" stored="true" docValues="true"/>
    <field name="record_type" type="string" indexed="true" stored="true" multiValued="false" docValues="true"/>
        <field name="referrer_url" type="string" indexed="true" stored="true" multiValued="false" docValues="true"/>
<field name="status_code" type="int" indexed="true" stored="true" docValues="true" />
```

**Comment by bnfleb** [comment]
This question also interests us.

I did some tests on the schema by changing every `stored="true" docValues="true"` into `stored="false" docValues="true"`. The index is indeed smaller (about 5% smaller for ~1000 documents).
And updating a document can still be done without loosing data.

**Comment by tokee** [comment]
I just performed an experiment with Solr 7: For all atomic fields (`string`, `int`, ...) I tried the 4 different combinations of docValues & stored. This was with 50 WARC files for a total of 1.6M documents. The total index sizes (using 1 shard) was

| Attributes | MByte |
| :--- | ---: |
| DV | 7,253 |
| Stored | 8,992 |
| DV&stored | 10,360 |
| Neither | 5,635 |

Quick sanity check:
* `(DV-Neither) + (Stored-Neither)` = 4978 MByte
* `DV&Stored-Neither` = 4725 MByte

That's only a 5% difference, which I'll attribute to jitter.

What this means in the greater picture is that we save space by using _docValues_ instead of _stored_ _and_ we gain the possibility of doing low (or at least lower) cost faceting, grouping & sorting on those fields. Win win.

Technical note: _docValues_ and _stored_ are Solr-internally two very different ways of persisting values. _stored_ field content is compressed and grouped with other _stored_ fields, with document as the connector. _docValues_ are independent arrays of values. String fields with little content does not compress very well and _docValues_ re-uses duplicate content, so it is not strange that the atomic fields are better served using _docValues_.

**Comment by tokee** [comment]
This is now in pull request #148 (Solr 7), should anyone feel adventurous.

**Comment by tokee** [comment]
The pull request #148 has been merged, so I'm closing this issue.
